events {}

http {
    server {
        listen 443 ssl;

        server_name api.local.test;

        ssl_certificate /certs/api.local.test.pem;
        ssl_certificate_key /certs/api.local.test-key.pem;

        location / {
            proxy_pass https://api:8443;
        }
    }

    server {
        listen 443 ssl;

        server_name app.local.test;

        ssl_certificate /certs/app.local.test.pem;
        ssl_certificate_key /certs/app.local.test-key.pem;

        location / {
            proxy_pass https://app:8444;
        }
    }
}
